### ISSUE TITLE
How to customise the output?

### ISSUE THREAD

**Issue by jaydonga** [HexarA/Json2Pojo#1]
For example if I need output for plain JSON consumption, and not using GSON library, want primitive int types instead of objects, how can I customise?

**Comment by HexarA** [comment]
I'm not sure what you mean by plain JSON consumption - are you planning to use a different parser? Or do you just want to suppress GSON annotations?

Obviously there are a lot of options you might want to customize, but the current scope of this plugin is to support GSON parsing via POJOs only, and the options to use Long/Double versus Integer/Float or primitives is kind of hardcoded right now. Until I can come up with a reasonable way to choose among options, you might want to fork/modify to get the plugin options that you want =)

**Comment by HexarA** [comment]
Closing as this isn't really a "real" issue.
