### ISSUE TITLE
Generate fields with lower case first letter

### ISSUE THREAD

**Issue by firov** [HexarA/Json2Pojo#13]
Java code style requires lower case for first letter
https://docs.oracle.com/javase/tutorial/java/nutsandbolts/variables.html

> If the name you choose consists of only one word, spell that word in all lowercase letters. If it consists of more than one word, capitalize the first letter of each subsequent word.

**Comment by wf-chris-hughes** [comment]
@HexarA Can you review and merge this PR. Thanks

**Comment by HexarA** [comment]
Merged #14. Sorry for the delay =)
