### ISSUE TITLE
Generate child class as inner class

### ISSUE THREAD

**Issue by ravirupareliya** [HexarA/Json2Pojo#4]
Currently it is creating seperate classes for inner class, does there any way to create those classes inside main class only? As a child class.

For example if i will add this Json {"data":{"name":"abc","data1":{"key":"value"}}}, it will create 2 seperate classes with seperate java files in package with name Data and Data1. Is it possible to create main class as given name and then other classes as inner class of that main class?

**Comment by HexarA** [comment]
This would work fine for very simple JSON sources that would never need to re-use child objects with the same name, but one of the main goals of this particular plugin / implementation is that any named objects / array objects are assumed to be the same and can be re-used among all generated classes within a package. So I'm not particularly inclined to offer this as an option or to go in this direction - but if you really need this functionality, you can always fork and modify for your own use =)
