### ISSUE TITLE
Plugin error on Android Studio 2.2.3

### ISSUE THREAD

**Issue by bkmalkoc** [HexarA/Json2Pojo#6]
![capture](https://cloud.githubusercontent.com/assets/11876911/22003829/915dad20-dc0b-11e6-9cda-dcf7fefaf2d9.JPG)

**Comment by HexarA** [comment]
Do you have a stack trace or any other info on how this error was caused, such as the source input and plugin version?

**Comment by HexarA** [comment]
Nevermind, I was able to reproduce this by right-clicking on a file instead of a folder / package. Fixed in 1.0.6 [here](https://github.com/HexarA/Json2Pojo/commit/53d664e81dd24576bf8d1491cb15de47571e38ad)
