### ISSUE TITLE
Cannot generate class

### ISSUE THREAD

**Issue by ClaudeHangui** [HexarA/Json2Pojo#7]
When trying to generate a pojo this is what I get:

Codegen Failed

java.lang.IllegalArguementException: JClass name Version-history contains illegal character -

**Comment by HexarA** [comment]
You must have a hyphen in a JSON field name, eg. "Version-history". I should filter out non-valid characters from class/field/parameter names. Fix incoming soon. Thanks for raising the issue.

**Comment by HexarA** [comment]
Fixed in 1.0.7 - please update the plugin.
